Update
acidnik/ppcp pull request #7
Opened 2024-01-07 15:48 UTC by stephin-thomas

Remove deprecated dependencies and replace with newer alternatives. Change rust edition and syntax to 2021 edition.

2024-01-08 04:25 UTC, acidnik requested changes
thanks for the PR! looks good, but please remove unnecessary commented code

2024-01-08 04:25 UTC, acidnik commented on src/app.rs
> +        // let pb_done2 = pb_done.clone();
this doesn't seems right

2024-05-21 20:28 UTC, noamraph commented
@acidnik I want to try to add parallelization to ppcp (I'm on a slow NFS, and copying a lot of files is VERY slow). I wanted to see if I can help with this PR.

I added a commit to it, and opened another PR so it will be easier to view the changes: https://github.com/acidnik/ppcp/pull/8

Regarding the removal of pb_done: now there's no need, and you can't, call `.join()` of indicatif. So I think there's no reason to have the extra mutex at all. In my PR I just removed it.

WDYT?

2024-05-22 08:58 UTC, acidnik commented
@noamraph I still don't see how parallelization would speed up your network, but if you implement it and prove that it is faster (by showing the before/after numbers) I will merge the PR

2024-05-22 09:00 UTC, merged

2024-05-22 12:25 UTC, noamraph commented
> @noamraph I still don't see how parallelization would speed up your network, but if you implement it and prove that it is faster (by showing the before/after numbers) I will merge the PR

Great, thanks! I have already seen parallelization give a very large benefit, with `rclone --multi-thread-streams=100`. The reason is that the NFS where I work has a pretty significant latency, and a high throughput. For example (pretty realistic), I can copy a single large file at 100MB/s, but copying each file takes 10ms no matter its size. So when I have a directory structure with 1M files 1kB each, copying it sequentially takes 3 hours, but copying one 1GB file takes 10 seconds. Parallelization makes everything much less latency-sensitive - having 100 threads can reduce the 3 hours to 100 or 200 seconds.